build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true

console-reports:
  active: true
  exclude:
     - 'ProjectStatisticsReport'
     - 'ComplexityReport'
     - 'NotificationReport'
     - 'FindingsReport'
     - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
     - 'HtmlOutputReport'
     - 'TxtOutputReport'
     - 'XmlOutputReport'
     - 'SarifOutputReport'

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ForbiddenComment:
    active: false

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15
